### PR TITLE
add gpgwrapper.ExportPrivateKey(...) and tests

### PR DESCRIPTION
**Pull request by paulfurley**

### CODE REVIEW

**Comment by paulfurley** [comment]
This needs rebasing after #53 then I think it'll pass

**Comment by paulfurley** [comment]
Erm. What happened to the commits?

**Comment by paulfurley** [comment]
By "rebased" do you mean, "replaced all the code with a different commit" ?

**Comment by idrysdale** [comment]
Oops! Weird.

I *thought* I just fetched it, then ran `git rebase master`, but appears not!

🤦‍♂️

**Comment by paulfurley** [comment]
Seems older versions of GnuPG version 2 don't support pinentry mode:

https://bugzilla.redhat.com/show_bug.cgi?id=1582209

Bad news is, we're probably gonna have to develop a workaround for different versions and switch on the version...

**Pull request closed without merging**
