### PR TITLE
Prompt to automatically rotate successfully rotated keys

### PR DESCRIPTION
**Pull request by idrysdale**
Rebase after https://github.com/fluidkeys/fluidkeys/pull/154

### CODE REVIEW

**Comment by idrysdale** [comment]
Rebase after 154

**Comment by paulfurley** [comment]
Rebased.

**Comment by paulfurley** [comment]
I ran this for a new key, said "yes", then ran it again and it prompted me again.

Of course! It should only prompt if `Config.ShouldRotateAutomatically(key) == false`

**Comment by idrysdale** [comment]
Ah, yes - good spot! :-)

**Comment by paulfurley** [comment]
Hmm I just realised there was no error checking on any of these :\

**Pull request merged**
