### PR TITLE
`fk status`: Print orphaned keys

### PR DESCRIPTION
**Pull request by idrysdale**
Rebase after https://github.com/fluidkeys/fluidkeys/pull/444

Looks like this:
Screenshot 2019-03-22 at 17 47 46

### CODE REVIEW

**Comment by paulfurley** [comment]
rebasing

**Comment by paulfurley** [comment]
image

^^ It's a bit overwhelming getting the "You're not in a team" message 3 times.

A header in between would help. Or only showing it once?

I'd actually expected these orphaned keys to show up in a table basically matching `fk key list`

**Comment by idrysdale** [comment]
I've updated it, so it should now look more like this:

Screenshot 2019-03-25 at 11 28 55

**Comment by paulfurley** [comment]
testing now!

**Pull request closed without merging**
